# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foreignbuddy' do
  pod 'Firebase/Core'
  use_frameworks!

  # Pods for foreignbuddy

  target 'foreignbuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foreignbuddyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
