# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ForeignBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForeignBuddy
  pod 'Firebase/Core'

  target 'ForeignBuddyTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'ForeignBuddyUITests' do
    inherit! :complete
    # Pods for testing
  end

end
