# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ForeignBuddyIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForeignBuddyIOS
	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'JSQMessagesViewController'

    pod 'SDWebImage', '~>3.8'
  target 'ForeignBuddyIOSTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'ForeignBuddyIOSUITests' do
    inherit! :complete
    # Pods for testing
  end

end
